# Generated by Django 6.1 on 2026-09-17 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieActualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('couleur', models.CharField(default='#1565c0', max_length=7)),
            ],
            options={
                'verbose_name': "Catégorie d'actualité",
                'verbose_name_plural': "Catégories d'actualités",
            },
        ),
        migrations.CreateModel(
            name='CategorieJournaliste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('icone', models.CharField(blank=True, help_text='Font Awesome icon class, e.g. fas fa-globe', max_length=50)),
                ('couleur', models.CharField(default='#1565c0', help_text='Hex color code', max_length=7)),
            ],
            options={
                'verbose_name': 'Catégorie de journaliste',
                'verbose_name_plural': 'Catégories de journalistes',
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/')),
                ('description', models.TextField(blank=True)),
                ('site_web', models.URLField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Journaliste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('nationalite', models.CharField(max_length=100)),
                ('ville_residence', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('lieu_service', models.CharField(blank=True, max_length=200)),
                ('departement', models.CharField(blank=True, max_length=100)),
                ('fonctions', models.CharField(max_length=200)),
                ('matricule', models.CharField(blank=True, max_length=50)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='journalistes/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('bio', models.TextField(blank=True, verbose_name='Parlez de vous')),
                ('type_journaliste', models.CharField(choices=[('interne', 'Interne'), ('externe', 'Externe')], default='externe', max_length=20)),
                ('performances', models.FloatField(default=0, help_text='Côte en pourcentage')),
                ('approuve', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('medias', models.CharField(blank=True, help_text='Ex: Presse écrite | Web | TV', max_length=200)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriejournaliste')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journaliste', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journaliste',
                'verbose_name_plural': 'Journalistes',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='actualites/')),
                ('titre', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('contenu', models.TextField()),
                ('lieu', models.CharField(max_length=200)),
                ('tache_effectuee', models.CharField(help_text='Rédaction, reportage, prise de vue...', max_length=200, verbose_name='Tâche effectuée')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('description_mission', models.TextField(blank=True, verbose_name='Décrire la mission')),
                ('status', models.CharField(default='Soumis', max_length=50)),
                ('note', models.FloatField(default=0, help_text='Note donnée par les correcteurs', verbose_name='Note brute')),
                ('performances', models.FloatField(default=0)),
                ('normes', models.FloatField(default=0, verbose_name='Respect des normes')),
                ('evaluation', models.FloatField(default=0, help_text='Moyenne auto-calculée', verbose_name='Évaluation')),
                ('commentaires_correcteurs', models.TextField(blank=True, verbose_name='Commentaires des correcteurs')),
                ('approuve', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categorieactualite')),
                ('journaliste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualites', to='core.journaliste')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('post_nom', models.CharField(max_length=100, verbose_name='Post-nom')),
                ('nationalite', models.CharField(max_length=100)),
                ('ville_residence', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('interet', models.CharField(max_length=200, verbose_name='Intéressé par')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='stagiaires/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('niveau_academique', models.CharField(choices=[('secondaire', 'Secondaire'), ('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('autre', 'Autre')], max_length=50)),
                ('etat_civil', models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], max_length=20)),
                ('bio', models.TextField(blank=True, verbose_name='Parlez de vous')),
                ('performances', models.FloatField(default=0)),
                ('nom_responsable', models.CharField(blank=True, max_length=200, verbose_name='Nom du responsable/formateur')),
                ('tel_responsable', models.CharField(blank=True, max_length=20)),
                ('matricule', models.CharField(blank=True, max_length=50)),
                ('approuve', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stagiaire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stagiaire',
                'verbose_name_plural': 'Stagiaires',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
